### ISSUE TITLE
FTB QUEST - MONIFACTORY - Invalid formatting! Can't nest multiple substitutes!

### ISSUE THREAD

**Issue by RussAlexei** [peunsu/mc-questing-mod-localizer#23]
Thank you for the program.
I translated FTB Quest (MONIFACTORY) - https://github.com/ThePansmith/Monifactory into Russian and encountered an error in some lines.
Error- Invalid formatting! Can't nest multiple substitutes!

Example of original line in file .snbt -
"[\"Text with \",{\"text\":\"underlines\",\"underlined\":true,\"hoverEvent\":{\"action\":\"show_text\",\"contents\":\"But not this!\"}},\" are (mostly) clickable.\"]"

Picture from the mod before the conversion procedure.

![Screenshot_2](https://github.com/peunsu/mc-questing-mod-localizer/assets/8597579/5dbf949c-489e-4172-bc8b-8386e2ca1909)

Line in the new generated file (Example in English) -
"mnf.a_harder_genesis.quests0.description6": "[\\\"Text with \\\",{\\\"text\\\":\\\"underlines\\\",\\\"underlined\\\":true,\\\"hoverEvent\\\":{\\\"action\\\":\\\"show_text\\\",\\\"contents\\\":\\\"But not this!\\\"}},\\\" are (mostly) clickable.\\\"]"

Picture from the mod after the conversion procedure

![Screenshot_1](https://github.com/peunsu/mc-questing-mod-localizer/assets/8597579/41615c57-c22e-45ca-a30d-e9cdeef7e234)

Is it possible to solve this problem?

**Comment by peunsu** [comment]
The cause of the issue was the ``kubejs`` compatibility problem with the formatted text in ``.snbt`` file.

To solve the issue, I made the localizer to skip the formatted text enclosed in brackets. (#24)

The side effect of this change is that **the localizer won't translate the formatted text**, so you need to translate it by editing the original ``.snbt`` quest file **manually**.

However, the `invalid formatting` errors will no longer occur with the converted quest files.

Thanks for reporting the issue :)
